- name: Enable or Disable Particular Web Server on haproxy 
  hosts: all
  gather_facts: true
  become: yes
  become_user: "root"
  become_method: "su"
  become_exe: 'sudo -p "Password: " su -'
  tasks:
     - include_vars: ./vars/enable_disable_httpd_on_ha_vars.yml
     - shell: "{{haproxy_enable_disable_cmd}} {{enable_disable_webserver}} {{web_server}}"
       args:
         executable: "{{shell_type}}"
       register: output

     - debug:
         msg: "{{ output.stdout.split('\n') }}"
  

